services:

    nginx:
        image: ${COMPOSE_PROJECT_NAME}-nginx:latest
        build:
            context: ./docker/
            args:
                BUILD_ARGUMENT_ENV: dev
            dockerfile: ./nginx/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: always
        ports:
            - "${WEB_PORT_HTTP}:80"
            - "${WEB_PORT_SSL}:443"
        volumes:
            - ./:/var/www/html:ro,cached
        depends_on:
            - laravel
        networks:
            - laravel

    laravel: &laravel-template
        image: ${COMPOSE_PROJECT_NAME}-laravel:latest
        build:
            context: .
            args:
                BUILD_ARGUMENT_ENV: dev
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
                XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            dockerfile: ./Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-laravel
        volumes:
            - ./:/var/www/html:cached
        depends_on:
            - mysql
            - mail
        networks:
            - laravel

    ### Cron tasks
    supervisord:
        <<: *laravel-template
        container_name: ${COMPOSE_PROJECT_NAME}-supervisord
        expose: [ ]
        command: [ "/usr/bin/supervisord" ]

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - ./storage/mysql-dev-data:/var/lib/mysql:delegated
            - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - ./storage/redis-dev-data:/data
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mail:
        image: axllent/mailpit:latest
        container_name: ${COMPOSE_PROJECT_NAME}-mail
        restart: always
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - laravel

    chrome:
        image: 'browserless/chrome:latest'
        container_name: ${COMPOSE_PROJECT_NAME}-chrome
        ports:
            - '3000:3000'
        networks:
            - laravel

    scrapy:
        image: 'badouralix/python-scrapy:latest'
        build:
            context: .
            dockerfile: ./docker/scrapy/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-scrapy
        networks:
            - laravel

networks:
    laravel:
        name: laravel
volumes:
    laravel-redis:
        driver: local
